### PR TITLE
Add Twitter messaging. Truncats message >140 chars after url shortened.

### PR DESCRIPTION
**Pull request by junghao**
We save the returned http://t.co/XXXXXX url after we posted each time. And next time we'll measure our message length according to the latest t.co url.

Hope this makes sense.

The only chance this will fail is:
We posted an message with a long location name, plus t.co suddenly hashed a longer url than last time.

### CODE REVIEW

**Comment by junghao** [comment]
@quiffman What do you think

**Comment by quiffman** [comment]
Ah, I see.

So you're keeping the results from the previous posted tweet, as a reference to the likely length of the shortened URL?

It's a novel solution, but probably more work than strictly necessary.
You'll have to see if @gclitheroe thinks it passes the YAGNI test.

**Comment by gclitheroe** [comment]
It looks like it works but it is pretty complicated.  Why not just go with the length of the shortened URL that @quiffman pointed out before?

**Comment by junghao** [comment]
OK no problem.

**Comment by gclitheroe** [comment]
And your also linking pkg msg to pkg twitter:

```
func (q *Quake) AlertTwitter(minMagnitude float64, twitter twitter.Twitter) (alert bool, message string) {
```

Which I really don't like (circular dependencies)

**Pull request closed without merging**
