### PR TITLE
Observation message for FITS

### PR DESCRIPTION
**Pull request by gclitheroe**
A proposed message format for FITS messaging.

I've gone backwards and forwards on sending all site information at the same time or not.  My conclusion is including and updating site info adds a lot of DB writes and complexity for something that may never change.  

Using this message requires the following to be preloaded in the DB
```
NetworkID 
SiteID
TypeID
MethodID
```
but after that it is very easy.

`SampleID` and `SystemID` stick around for completeness but so far have been `none`.

And this will doubtless fail on snap (it's a snap bug).

### CODE REVIEW

**Comment by ozym** [comment]
Snap CI is having problems: "godep: No Godeps found (or in any parent directory)"

**Comment by gclitheroe** [comment]
yeah the snap thing is something to do with pull request pipelines on that build.  For some reason it gets an old build config and I haven't had the energy to remake the plan or bug report them yet.

**Comment by ozym** [comment]
Figured it was something like that, but just in case it was a new style error...

I see you've removed "receiptHandle" from the haz struct, I'm assuming this was the last step of removing this fuctionality.

**Comment by gclitheroe** [comment]
the receiptHandle was hanging round from my over eager interface for message processing.   I don't think anything was using it...

I've removed godeps from this (because it doesn't work for libs) but snap PR builds only haven't caught up with this.

**Comment by ozym** [comment]
Could there be a way of "Registering" a site, i.e. on start-up or every "now and then" a _Register_ site message could go through to update or create site information. The only tricky bit is that there's no feedback as to whether it was acted on (hence the replay) but this might not be too bad.

**Comment by gclitheroe** [comment]
Yes definitely. This is the tight loop I've been running in (over and over).  If you look at msg.Haz it carries several messages.  We could have something like this msg.Haz such as:

```
type struct Fits {
* Site
* Observation
}
```  
Then the consumer has to type switch to decide what to do with the message like this:

https://github.com/GeoNet/haz-web-consumer/blob/master/haz-web-consumer.go#L86

Very straight forwards if that is better.  What I keep trying to avoid is having to update or check site information for every Observation message.

**Comment by ozym** [comment]
I like the sound of that, I was worried the "preloaded in the DB"  would becoma a whole set of new processes that need to be loved and react to changes in delta etc.

**Comment by gclitheroe** [comment]
Righty dokey.  Good plan.

**Pull request closed without merging**
