### PR TITLE
Receive from SQS.

### PR DESCRIPTION
**Pull request by gclitheroe**
This code implements channels for receiving messages from AWS SQS.  

It greatly simplifies receiving messages from SQS in client code (the example on InitRx is really all you need to do).

The public interface is intended make it possible to switch the SQS client from github.com/AdRoll/goamz/sqs to the official AWS one (https://github.com/awslabs/aws-sdk-go/tree/master/service/sqs) when it becomes stable.  This could then be done with no changes need to client code.

It might be useful to read this https://golang.org/doc/effective_go.html#interfaces_and_types and maybe this https://inconshreveable.com/07-08-2014/principles-of-designing-go-apis-with-channels/

@ozym  - you may be interested as well.

### CODE REVIEW

**Comment by gclitheroe** [comment]
I don't know why this is failing on snap.  It's annoying.  I suspect it's to do with Godeps and multi level dependencies.  It certainly passes for me locally.

**Comment by ozym** [comment]
sqs/sqs.go:5:2: cannot find package "github.com/AdRoll/goamz/sqs" in any of:

**Comment by ozym** [comment]
from the details button ... never done this before looks quite interesting.

**Comment by gclitheroe** [comment]
I've fixed the pipeline.  It's not totally satisfactory.  I think this is to do with Godep not recursing into child directories to look for Godeps.

It probably means msg and msg/sqs should be two separate builds or something.

**Comment by gclitheroe** [comment]
InitRx should take cfg.SQS as an argument instead of having another SQS struct.  As per great suggestion from @junghao

**Pull request closed without merging**
