### PR TITLE
Add volcano alert tags for Urban Airship.

### PR DESCRIPTION
**Pull request by junghao**
Is this OK?

### CODE REVIEW

**Comment by gclitheroe** [comment]
Hi,

Am I right in thinking that you are suggesting the users would subscribe to different alert levels at difference volcanoes?  Is that what the tags you have here are for?

The idea is that an app user will get _all_ alert level change notifications for all volcanoes.  There is no option to select one volcano and no option to set alert levels.

The level changes maybe 1 per year so there should be no need to filter them.

**Comment by junghao** [comment]
Yes that's what I thought in the beginning. But Kevin said that's possible if there's a volcano changed to level 3 then there could be a lot of alerts in a day so it's possible that users might need them.

**Comment by gclitheroe** [comment]
Ah right I kind of understand now.  Interesting.

**Comment by junghao** [comment]
We can just keep these tags' format. If we don't want the filter then just set everyone's tag to 0@all. However, now everything is going to push a notification ( according to yesterday's wiki and your mail ) so I have no idea how to deal with these now.

**Comment by gclitheroe** [comment]
OK - I need to read the wiki as well.

**Comment by junghao** [comment]
I'm not really want to merge this. Just want to make sure I'm on the right direction.

**Pull request closed without merging**
